#!/usr/bin/env python3
"""
Visualize analysis metrics over time.

This script reads the metrics.csv file generated by analyze1.py and creates
time-series plots showing brightness, contrast, and streak counts over time.

Usage:
    python tools/visualize.py <night_dir> [--output <output_dir>] [--show]

Examples:
    python tools/visualize.py ./night_2025-12-24
    python tools/visualize.py ./night_2025-12-24 --show
    python tools/visualize.py ./night_2025-12-24 --output ./custom_plots
"""

import argparse
import csv
from pathlib import Path
import sys
import matplotlib.pyplot as plt
import matplotlib


def load_metrics(metrics_path: Path) -> dict:
    """
    Load metrics from CSV file.
    
    Args:
        metrics_path: Path to metrics.csv file
        
    Returns:
        Dictionary with lists of values for each metric
    """
    if not metrics_path.exists():
        print(f"Error: Metrics file not found: {metrics_path}", file=sys.stderr)
        print("Run analyze1.py first to generate metrics.", file=sys.stderr)
        sys.exit(1)
    
    data = {
        'files': [],
        'mean_brightness': [],
        'star_contrast': [],
        'streak_count': []
    }
    
    try:
        with open(metrics_path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                data['files'].append(row['file'])
                data['mean_brightness'].append(float(row['mean_brightness']))
                data['star_contrast'].append(float(row['star_contrast']))
                data['streak_count'].append(int(row['streak_count']))
    except Exception as e:
        print(f"Error reading metrics file: {e}", file=sys.stderr)
        sys.exit(1)
    
    if not data['files']:
        print("Error: No data found in metrics file.", file=sys.stderr)
        sys.exit(1)
    
    return data


def create_plots(data: dict, output_dir: Path, show: bool = False, event_threshold: int = 2):
    """
    Create and save visualization plots.
    
    Args:
        data: Dictionary with metric data
        output_dir: Directory to save plots
        show: Whether to display plots interactively
        event_threshold: Minimum streak count to highlight as event (default: 2, should match config)
    """
    # Set matplotlib backend based on display mode
    # Must be set before creating any figures
    if not show:
        matplotlib.use('Agg')  # Non-interactive backend for file output only
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    frame_numbers = list(range(1, len(data['files']) + 1))
    
    # Plot 1: Mean Brightness Over Time
    plt.figure(figsize=(12, 5))
    plt.plot(frame_numbers, data['mean_brightness'], 'b-', linewidth=2, marker='o', markersize=3)
    plt.xlabel('Frame Number', fontsize=12)
    plt.ylabel('Mean Brightness', fontsize=12)
    plt.title('Sky Brightness Over Time', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    brightness_path = output_dir / 'brightness_over_time.png'
    plt.savefig(brightness_path, dpi=150)
    print(f"Saved: {brightness_path}")
    
    if show:
        plt.show()
    plt.close()
    
    # Plot 2: Star Contrast Over Time
    plt.figure(figsize=(12, 5))
    plt.plot(frame_numbers, data['star_contrast'], 'g-', linewidth=2, marker='o', markersize=3)
    plt.xlabel('Frame Number', fontsize=12)
    plt.ylabel('Star Contrast (std dev)', fontsize=12)
    plt.title('Star Contrast Over Time', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    contrast_path = output_dir / 'contrast_over_time.png'
    plt.savefig(contrast_path, dpi=150)
    print(f"Saved: {contrast_path}")
    
    if show:
        plt.show()
    plt.close()
    
    # Plot 3: Streak Count Per Frame
    plt.figure(figsize=(12, 5))
    colors = ['red' if count >= event_threshold else 'blue' for count in data['streak_count']]
    plt.bar(frame_numbers, data['streak_count'], color=colors, alpha=0.7)
    plt.xlabel('Frame Number', fontsize=12)
    plt.ylabel('Streak Count', fontsize=12)
    plt.title(f'Detected Streaks Per Frame (Red = Event with {event_threshold}+ streaks)', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()
    
    streaks_path = output_dir / 'streak_counts.png'
    plt.savefig(streaks_path, dpi=150)
    print(f"Saved: {streaks_path}")
    
    if show:
        plt.show()
    plt.close()
    
    # Plot 4: Combined Overview
    fig, axes = plt.subplots(3, 1, figsize=(14, 10))
    
    # Brightness
    axes[0].plot(frame_numbers, data['mean_brightness'], 'b-', linewidth=1.5)
    axes[0].set_ylabel('Mean Brightness', fontsize=10)
    axes[0].set_title('Analysis Metrics Overview', fontsize=14, fontweight='bold')
    axes[0].grid(True, alpha=0.3)
    
    # Contrast
    axes[1].plot(frame_numbers, data['star_contrast'], 'g-', linewidth=1.5)
    axes[1].set_ylabel('Star Contrast', fontsize=10)
    axes[1].grid(True, alpha=0.3)
    
    # Streaks
    colors = ['red' if count >= event_threshold else 'blue' for count in data['streak_count']]
    axes[2].bar(frame_numbers, data['streak_count'], color=colors, alpha=0.7)
    axes[2].set_xlabel('Frame Number', fontsize=10)
    axes[2].set_ylabel('Streak Count', fontsize=10)
    axes[2].grid(True, alpha=0.3, axis='y')
    
    plt.tight_layout()
    
    overview_path = output_dir / 'overview.png'
    plt.savefig(overview_path, dpi=150)
    print(f"Saved: {overview_path}")
    
    if show:
        plt.show()
    plt.close()


def main():
    parser = argparse.ArgumentParser(
        description="Visualize analysis metrics from starplate-analysis output",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python tools/visualize.py ./night_2025-12-24
  python tools/visualize.py ./night_2025-12-24 --show
  python tools/visualize.py ./night_2025-12-24 --output ./custom_plots
  
Output files (saved to <night_dir>/plots/ by default):
  - brightness_over_time.png: Sky brightness trend
  - contrast_over_time.png: Star visibility metric
  - streak_counts.png: Detected streaks per frame
  - overview.png: Combined view of all metrics
"""
    )
    
    parser.add_argument(
        'night_dir',
        help='Path to night directory containing metrics.csv'
    )
    parser.add_argument(
        '-o', '--output',
        help='Output directory for plots (default: <night_dir>/plots/)',
        default=None
    )
    parser.add_argument(
        '-s', '--show',
        help='Display plots interactively (requires X11/display)',
        action='store_true'
    )
    
    args = parser.parse_args()
    
    # Validate input directory
    night_dir = Path(args.night_dir)
    if not night_dir.exists():
        print(f"Error: Directory '{args.night_dir}' does not exist.", file=sys.stderr)
        sys.exit(1)
    
    # Load metrics
    metrics_path = night_dir / 'metrics.csv'
    print(f"Loading metrics from {metrics_path}...")
    data = load_metrics(metrics_path)
    print(f"Loaded {len(data['files'])} frames")
    
    # Determine output directory
    if args.output:
        output_dir = Path(args.output)
    else:
        output_dir = night_dir / 'plots'
    
    # Create plots
    print(f"\nCreating plots in {output_dir}...")
    create_plots(data, output_dir, args.show)
    
    print(f"\nVisualization complete!")
    print(f"Total frames: {len(data['files'])}")
    print(f"Frames with streaks: {sum(1 for c in data['streak_count'] if c > 0)}")
    print(f"Total streaks detected: {sum(data['streak_count'])}")


if __name__ == '__main__':
    main()
